import { describe, expect, it } from 'vitest';
import { AR_MARKERS } from '../src/ar/markerCatalog';
import { renderAppShell } from '../src/ui/appShell';

describe('renderAppShell', () => {
  it('renders route navigation, separate workflow pages, and both marker images', () => {
    const container = document.createElement('div');
    container.innerHTML = renderAppShell(AR_MARKERS);
    const html = container.innerHTML;

    expect(html).toContain('href="#/scan"');
    expect(html).toContain('href="#/base"');
    expect(html).toContain('href="#/models"');
    expect(html).toContain('href="#/targets"');
    expect(html).toContain('href="#/markers"');
    expect(html).toContain('href="#/account"');
    expect(html).toContain('data-page="home"');
    expect(html).toContain('data-page="scan"');
    expect(html).toContain('data-page="base"');
    expect(html).toContain('data-page="models"');
    expect(container.querySelector('[data-page="targets"]')).toBeTruthy();
    expect(html).toContain('data-page="markers"');
    expect(html).toContain('data-page="account"');
    expect(html).toContain('id="ar-stage"');
    expect(html).toContain('id="start-ar"');
    expect(html).toContain('id="worker-email"');
    expect(html).toContain('id="base-capture-video"');
    expect(html).toContain('id="process-base-image"');
    expect(html).toContain('id="cloudflare-model-select"');
    expect(container.querySelector('#target-image-file')).toBeTruthy();
    expect(container.querySelector('#target-model-select')).toBeTruthy();
    expect(container.querySelector('#add-target-object')).toBeTruthy();
    expect(container.querySelector('#remove-target-object')).toBeTruthy();
    expect(container.querySelector('#target-object-list')).toBeTruthy();
    expect(container.querySelector('#target-scale')).toBeTruthy();
    expect(container.querySelector('#target-scale-x')).toBeNull();
    expect(container.querySelector('#target-scale-y')).toBeNull();
    expect(container.querySelector('#target-scale-z')).toBeNull();
    expect(container.querySelector('#target-rotation-x')).toBeTruthy();
    expect(container.querySelector('#target-rotation-y')).toBeTruthy();
    expect(container.querySelector('#target-rotation-z')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="move"][data-reset-axis="all"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="move"][data-reset-axis="x"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="move"][data-reset-axis="y"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="move"][data-reset-axis="z"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="rotate"][data-reset-axis="all"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="rotate"][data-reset-axis="x"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="rotate"][data-reset-axis="y"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="rotate"][data-reset-axis="z"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="scale"][data-reset-axis="all"]')).toBeTruthy();
    expect(container.querySelector('[data-reset-transform="scale"][data-reset-axis="x"]')).toBeNull();
    expect(container.querySelector('[data-reset-transform="scale"][data-reset-axis="y"]')).toBeNull();
    expect(container.querySelector('[data-reset-transform="scale"][data-reset-axis="z"]')).toBeNull();
    expect(container.querySelector('[data-transform-mode="translate"]')).toBeTruthy();
    expect(container.querySelector('[data-transform-mode="rotate"]')).toBeTruthy();
    expect(container.querySelector('[data-transform-mode="scale"]')).toBeTruthy();
    expect(container.querySelector('#target-camera-distance')).toBeTruthy();
    expect(container.querySelector('#target-camera-height')).toBeTruthy();
    expect(container.querySelector('#target-camera-yaw')).toBeTruthy();
    expect(container.querySelector('#target-camera-gizmo')).toBeTruthy();
    expect(container.querySelector('[data-camera-preset="top"]')).toBeTruthy();
    expect(container.querySelector('[data-camera-preset="front"]')).toBeTruthy();
    expect(container.querySelector('[data-camera-preset="right"]')).toBeTruthy();
    expect(container.querySelector('[data-camera-preset="home"]')).toBeTruthy();
    expect(container.querySelector('#target-spin-axis')).toBeTruthy();
    expect(container.querySelector('#target-spin-speed')).toBeTruthy();
    expect(container.querySelector('#target-spin-axis option[value="y"]')?.hasAttribute('selected')).toBe(true);
    expect((container.querySelector('#target-spin-speed') as HTMLInputElement).value).toBe('0');
    expect(container.querySelector('#target-bob-height')).toBeTruthy();
    expect(container.querySelector('#target-bob-speed')).toBeTruthy();
    expect(container.querySelector('#reset-target-animation')).toBeTruthy();
    expect(container.querySelector('#target-preview-stage')).toBeTruthy();
    expect(container.querySelector('#save-image-target')).toBeTruthy();
    expect(container.querySelector('#saved-image-target-list')).toBeTruthy();
    expect(html).toContain('id="reload-cloudflare-models"');
    expect(html).toContain('Marker AR studio');
    expect(html).toContain('Web-AR Worker');

    for (const marker of AR_MARKERS) {
      expect(html).toContain(marker.label);
      expect(html).toContain(marker.imagePath);
      expect(html).toContain(`download="${marker.id}.svg"`);
    }
  });
});
